<?php
/**
 * @file
 * Provides the Provision_Config_Drushrc_Alias class.
 */

/**
 * Class to write an alias records.
 */
class Provision_Config_Drushrc_Alias extends Provision_Config_Drushrc {
  public $template = 'provision_drushrc_alias.tpl.php';

  /**
   * @param $name
   *   String '\@name' for named context.
   * @param $options
   *   Array of string option names to save.
   */
  function __construct($context, $data = array()) {
    parent::__construct($context, $data);

    if (isset($data['aliases']) && is_array($data['aliases'])) {
      $data['aliases'] = array_unique($data['aliases']);
    }
    if (isset($data['drush_aliases']) && is_array($data['drush_aliases'])) {
      $data['drush_aliases'] = array_unique($data['drush_aliases']);
    }

    $this->data = array(
      'aliasname' => str_replace('.', '_', ltrim($context, '@')),
      'options' => $data,
      'environment_name' => isset($data['environment_name'])? $data['environment_name'] : 'default',
    );


    // @TODO: If this is a site, write a drush YML alias as well.

  }

  function filename() {
    return drush_server_home() . '/.drush/' . $this->data['aliasname'] . '.alias.drushrc.php';
  }

  function filenameYaml() {
    return drush_server_home() . '/.drush/sites/' . $this->data['aliasname'] . '.site.yml';
  }

  function write()
  {
    $this->writeSiteAlias();
    return parent::write(); // TODO: Change the autogenerated stub
  }

  /**
   * Write a Drush 9+ YML drush alias.
   * @return void
   */
  function writeSiteAlias() {
    $alias = [
      $this->data['environment_name'] => [
        'root' => isset($this->data['options']['root'])? $this->data['options']['root']: d('hostmaster')->root,
        'uri' => isset($this->data['options']['uri']) ? $this->data['options']['uri'] : NULL,
        'options' => $this->data['options'],
      ],
    ];
    $yaml = \Symfony\Component\Yaml\Yaml::dump($alias, 10, 2);
    $filename = $this->filenameYaml();

    provision_file()->file_put_contents($filename, $yaml)
      ->succeed('Wrote Yaml Drush Site Alias file: ' . $filename, 'success')
      ->fail('Could not write Yaml Drush Site Alias file: ' . $filename)
      ->status();
  }
}
