<?php
/**
 * @file
 * Template file for a Backdrop settings.php.
 */
print '<?php' ?>

/**
 * @file Backdrop's settings.php file
 *
 * This file was automatically generated by Aegir <?php print $this->version; ?>

 * on <?php print date('r'); ?>.
 *
 * If it is still managed by Aegir, changes to this file may be
 * lost. If it is not managed by aegir, you should remove this header
 * to avoid further confusion.
 */

<?php if ($subdirs_support_enabled): ?>
/**
 * Detecting subdirectory mode
 */
if (isset($_SERVER['SITE_SUBDIR']) && isset($_SERVER['RAW_HOST'])) {
  $base_url = 'http://' . $_SERVER['RAW_HOST'] . '/' . $_SERVER['SITE_SUBDIR'];
  $cookie_domain = "." . $_SERVER['RAW_HOST'];
  ini_set('session.cookie_path', '/' . $_SERVER['SITE_SUBDIR'] . '/');
}
<?php endif; ?>

<?php if ($this->cloaked): ?>
if (!isset($_SERVER['db_name']) && PHP_SAPI == 'cli') {
  /**
   * Command line has no vhost, so none of the fastcgi_param credentials below
   * are set. Recover them from the sibling drushrc.php, which carries the same
   * values and is group-restricted to the shell identities -- the web server
   * user is not in that group and can never read it, so the credentials stay
   * out of reach of site PHP. Drush 8 loads that file by itself; a site-local
   * modern Drush (the `vdrush` alias in the limited shell) does not, which is
   * why it is read explicitly here. Parsed, never included: the file is Drush
   * configuration and must not execute as part of settings.php.
   * PHP_SAPI is a routing test only -- the group on the file is the control.
   */
  $aegir_rc_file = dirname(__FILE__) . '/drushrc.php';
  if (is_readable($aegir_rc_file)) {
    $aegir_rc_body = file_get_contents($aegir_rc_file);
    if ($aegir_rc_body !== FALSE) {
      $aegir_rc_keys = array('db_type', 'db_host', 'db_user', 'db_passwd', 'db_name', 'db_port');
      foreach ($aegir_rc_keys as $aegir_rc_key) {
        $aegir_rc_match = array();
        if (preg_match('/\$options\[\'' . $aegir_rc_key . '\'\]\s*=\s*\'([^\']*)\';/', $aegir_rc_body, $aegir_rc_match)) {
          $_SERVER[$aegir_rc_key] = $aegir_rc_match[1];
        }
      }
      unset($aegir_rc_body, $aegir_rc_keys, $aegir_rc_key, $aegir_rc_match);
    }
  }
  unset($aegir_rc_file);
}
if (!empty($_SERVER['db_creds_urlencoded'])) {
  /**
   * The vhost emits the six credentials urlencode()d so that no value can
   * break the web server's config syntax. The uncloaked branch of this
   * template decodes them once (the per-CMS Settings.php class), so without
   * this the cloaked web tier was the only path authenticating with the
   * ESCAPED form -- breaking any adopted site whose password contains '@',
   * '#' or '!' while its CLI tier kept working.
   *
   * Decode ONLY the vhost-sourced set. The drushrc.php recovery above, and
   * the credentials exported into the environment for a spawned site-local
   * Drush, both carry RAW values; decoding those would corrupt them instead.
   * The marker is emitted next to the credentials themselves, so it is
   * present exactly when they are encoded.
   */
  $aegir_enc_keys = array('db_type', 'db_host', 'db_user', 'db_passwd', 'db_name', 'db_port');
  foreach ($aegir_enc_keys as $aegir_enc_key) {
    if (isset($_SERVER[$aegir_enc_key])) {
      $_SERVER[$aegir_enc_key] = urldecode($_SERVER[$aegir_enc_key]);
    }
  }
  unset($aegir_enc_keys, $aegir_enc_key);
}
if (isset($_SERVER['db_name'])) {
  /**
   * The database credentials are stored in the Apache or Nginx vhost config
   * of the associated site with SetEnv (fastcgi_param in Nginx) parameters.
   * They are called here with $_SERVER environment variables to
   * prevent sensitive data from leaking to site administrators
   * with PHP access, that potentially might be of other sites in
   * Backdrop's multisite set-up.
   * This is a security measure implemented by the Aegir project.
   *
   * Backdrop's simplified scalar $database array (1.30.0+ form). The mysql
   * driver is forced; utf8mb4/utf8mb4_general_ci are Backdrop defaults for the
   * simple-array form (bootstrap.inc backdrop_settings_initialize()).
   */
  $database = array(
    'driver' => 'mysql',
    'database' => $_SERVER['db_name'],
    'username' => $_SERVER['db_user'],
    'password' => $_SERVER['db_passwd'],
    'host' => $_SERVER['db_host'],
    /* Backdrop interprets the port as a string, whereas Drush sees it as an
     * integer. To maintain consistency, we cast it to a string.
     */
    'port' => (string) $_SERVER['db_port'],
  );
  $database_prefix = '';
}

  /**
   * Now that we used the credentials from the apache environment, we
   * don't need them anymore. Clear them from apache and the _SERVER
   * array, otherwise they show up in phpinfo() and other friendly
   * places.
   */
  if (function_exists('apache_setenv')) {
    apache_setenv('db_type', null);
    apache_setenv('db_user', null);
    apache_setenv('db_passwd', null);
    apache_setenv('db_host', null);
    apache_setenv('db_port', null);
    apache_setenv('db_name', null);
    // no idea why they are also in REDIRECT_foo, but they are
    apache_setenv('REDIRECT_db_type', null);
    apache_setenv('REDIRECT_db_user', null);
    apache_setenv('REDIRECT_db_passwd', null);
    apache_setenv('REDIRECT_db_host', null);
    apache_setenv('REDIRECT_db_port', null);
    apache_setenv('REDIRECT_db_name', null);
  }
  unset($_SERVER['db_type']);
  unset($_SERVER['db_user']);
  unset($_SERVER['db_passwd']);
  unset($_SERVER['db_host']);
  unset($_SERVER['db_port']);
  unset($_SERVER['db_name']);
  unset($_SERVER['REDIRECT_db_type']);
  unset($_SERVER['REDIRECT_db_user']);
  unset($_SERVER['REDIRECT_db_passwd']);
  unset($_SERVER['REDIRECT_db_host']);
  unset($_SERVER['REDIRECT_db_port']);
  unset($_SERVER['REDIRECT_db_name']);
  // The marker that steered the decode above: not a credential, but it has no
  // business surviving into site PHP either.
  unset($_SERVER['db_creds_urlencoded']);
  unset($_SERVER['REDIRECT_db_creds_urlencoded']);

<?php else: ?>

  /**
   * BOA uncloaks the credentials into settings.php (provision_db_cloaking is
   * FALSE), so the literal-creds branch is the one that actually fires. Emitted
   * as Backdrop's simplified scalar $database array; mysql driver forced.
   */
  $database = array(
    'driver' => 'mysql',
    'database' => "<?php print $this->creds['db_name']; ?>",
    'username' => "<?php print $this->creds['db_user']; ?>",
    'password' => "<?php print $this->creds['db_passwd']; ?>",
    'host' => "<?php print $this->creds['db_host']; ?>",
    'port' => "<?php print $this->creds['db_port']; ?>",
  );
  $database_prefix = '';

<?php endif; ?>

  /**
   * Site configuration files location.
   *
   * A bare directory name (no leading '.', '/' or '\') is resolved relative to
   * conf_path() -- the directory holding this settings.php, i.e. sites/<uri> --
   * by config_get_config_directory(). So the values below land in
   * sites/<uri>/private/config/{active,staging}. Do NOT prefix them with
   * 'sites/<uri>/' or they would double-nest. Pinned inside the site's
   * private dir so BOA's backup/clone/restore (chdir sites/<uri> + tar .) and
   * the nginx private-dir deny both cover them, and so install_backdrop() never
   * rewrites this 0440 file (the path differs from the hashed files/ default).
   */
  $config_directories['active'] = 'private/config/active';
  $config_directories['staging'] = 'private/config/staging';

  /**
   * Salt for one-time login links, cancel links, form tokens, etc. Non-empty so
   * the installer never rewrites this read-only settings.php.
   */
  $settings['hash_salt'] = '<?php print $backdrop_hash_salt ?>';

  /**
   * BOA runs its own backups; disable Backdrop's update.php backup writer and
   * its telemetry POSTs.
   */
  $settings['backup_directory'] = FALSE;
  $settings['telemetry_enabled'] = FALSE;

  /**
   * Keep the Drupal 7 API compatibility layer on (BOA hosts D7-built contrib);
   * Backdrop core itself does not need it. Without this line the shim is off,
   * because this generated file replaces Backdrop's shipped settings.php which
   * enables it by default.
   */
  $settings['backdrop_drupal_compatibility'] = TRUE;

  /**
   * Keep update.php / restore.php access gated to privileged accounts.
   */
  $settings['update_free_access'] = FALSE;
  $settings['restore_free_access'] = FALSE;
  $settings['allow_authorize_operations'] = FALSE;

  /**
   * File paths (docroot-relative, unlike the conf_path-relative config dirs
   * above). The installer already sets the public path to sites/<uri>/files;
   * pin all three via Backdrop's system.core config overrides for parity with
   * the BOA Drupal templates.
   */
  $config['system.core']['file_public_path'] = 'sites/<?php print $this->uri ?>/files';
  $config['system.core']['file_private_path'] = 'sites/<?php print $this->uri ?>/private/files';
  $config['system.core']['file_temporary_path'] = 'sites/<?php print $this->uri ?>/private/temp';

  /**
  * PHP settings: (managed in BOA via site and platform level INI files)
  *
  * To see what PHP settings are possible, including whether they can
  * be set at runtime (ie., when ini_set() occurs), read the PHP
  * documentation at http://www.php.net/manual/en/ini.php#ini.list
  * and take a look at the .htaccess file to see which non-runtime
  * settings are used there. Settings defined here should not be
  * duplicated there so as to avoid conflict issues.
  */
  //ini_set('session.gc_probability', 1);
  //ini_set('session.gc_divisor', 100);
  //ini_set('session.gc_maxlifetime', 200000);
  //ini_set('session.cookie_lifetime', 2000000);

  /**
  * Set the umask so that new directories created by Backdrop have the correct permissions
  */
  umask(0002);

  # Aegir marker, read via variable_get('aegir_api') (Backdrop maps that to
  # $conf); kept in the D7 $conf form so that reader still sees it.
  $conf['aegir_api'] = <?php print $this->api_version ? $this->api_version : 0 ?>;

  /**
   * Note: Backdrop's maintenance mode is stored in state
   * (state_set('maintenance_mode', ...)), not in settings.php -- there is no
   * settings-level offline flag to write here. Aegir takes a disabled site
   * offline at the nginx layer (the http service renders the disabled vhost
   * when site_enabled is false), so the in-CMS maintenance flag is not toggled
   * by the enable/disable engines.
   */

  /**
   * Trusted Host Patterns support.
   */
  $settings['trusted_host_patterns'] = array(
<?php
  $esc_uri = str_replace('.', '\.', $this->uri);
  print "    '^{$esc_uri}\$',\n";
  foreach ($this->aliases as $alias_url) {
    $esc_alias = preg_replace(['/\./', '/\/.+/'], ['\.', ''], $alias_url);
    print "    '^{$esc_alias}\$',\n";
  }
?>
    '^localhost$',
    '^localhost\.*',
    '\.local$',
  );

  /**
   * If external request was HTTPS but internal request is HTTP, set $_SERVER['HTTPS'] so Backdrop detects the right scheme.
   */
  if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && isset($_SERVER['REQUEST_SCHEME'])) {
    if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' && $_SERVER["REQUEST_SCHEME"] == 'http') {
      $_SERVER['HTTPS'] = 'on';
    }
  }

<?php print $extra_config; ?>

  # Additional host wide configuration settings. Backdrop-specific ONLY: the
  # Drupal global /data/conf/global.inc carries valkey/redis and other
  # Drupal-oriented code that breaks Backdrop in many ways, so it is NEVER
  # included here (unlike the D7/D8 templates). A dedicated Backdrop-safe
  # /data/conf/global/global-bd.inc (generated by the BOA global-config layer)
  # is the proper home for any shared Backdrop settings; include it only if
  # present, with NO fallback to the Drupal global.
  if (is_readable('/data/conf/global/global-bd.inc')) {
    include_once('/data/conf/global/global-bd.inc');
  }

  # Additional platform wide configuration settings.
  <?php $this->platform->root = provision_auto_fix_platform_root($this->platform->root); ?>

  if (is_readable('<?php print $this->platform->root  ?>/sites/all/platform.settings.php')) {
    include_once('<?php print $this->platform->root ?>/sites/all/platform.settings.php');
  }

  # Additional platform wide configuration settings.
  if (is_readable('<?php print $this->platform->root  ?>/sites/all/settings.php')) {
    include_once('<?php print $this->platform->root ?>/sites/all/settings.php');
  }

  # Additional site configuration settings.
  if (is_readable('<?php print $this->site_path  ?>/local.settings.php')) {
    include_once('<?php print $this->site_path  ?>/local.settings.php');
  }
