<?php
/**
 * @file
 * Template for a Textpattern multisite private/config.php.
 *
 * Shape mirrors TXP's own setup_makeConfig() output plus the keys it never
 * emits but Percona 8.4 + the fleet require: dbengine (the TXP default is
 * MyISAM), table_collation (utf8mb4_unicode_ci exists on both Percona 5.7 and
 * 8.4; the 8.4 server default utf8mb4_0900_ai_ci does not exist on 5.7 --
 * mydumper moves between fleet halves), and NO client_flags key at all (TXP's
 * isset() test would discard its own FOUND_ROWS default).
 *
 * Cloaked (provision_db_cloaking, on by default under the BOA nginx service):
 * carries NO literal credentials, closing the cross-tenant read every
 * tenant's shared web_data group otherwise permitted (boa-private-notes
 * notes/2026-09-19-txp-edb51176-defence-audit.md). The web tier reads them
 * from the vhost's fastcgi_param db_* set (urlencode()d there, decoded here
 * via the db_creds_urlencoded marker -- same contract as the Drupal/Backdrop
 * settings.php templates); the one CLI consumer (the install shim,
 * txp-install-shim.php) reads them from the real process environment,
 * exported by provision_prepare_environment_subprocess() immediately before
 * the shim is spawned (txp/txp/install.inc) -- same mechanism the D8+ core
 * rebuild subprocess already uses for the same reason.
 */
print '<?php' ?>

/**
 * @file Textpattern config.php (Aegir-managed; re-rendered on every verify.
 * Manual edits will be lost.)
 *
 * Generated by Aegir <?php print $this->version; ?> on <?php print date('r'); ?>.
 */
<?php if ($this->cloaked): ?>
if (!empty($_SERVER['db_creds_urlencoded'])) {
  /**
   * The vhost emits the six credentials urlencode()d so that no value can
   * break the web server's config syntax. Decode ONLY the vhost-sourced set:
   * the install shim's environment-exported set is already raw and must not
   * be decoded again. The marker is emitted next to the credentials
   * themselves, so it is present exactly when they are encoded.
   */
  foreach (array('db_type', 'db_host', 'db_user', 'db_passwd', 'db_name', 'db_port') as $aegir_enc_key) {
    if (isset($_SERVER[$aegir_enc_key])) {
      $_SERVER[$aegir_enc_key] = urldecode($_SERVER[$aegir_enc_key]);
    }
  }
  unset($aegir_enc_key);
}
if (isset($_SERVER['db_name'])) {
  /**
   * The credentials live in the nginx vhost config (root-owned fastcgi_param)
   * for the web tier, or in the real process environment for the install
   * shim -- never as a literal in this file, which every tenant's web pool
   * shares the group of. This is the security measure that closes the
   * cross-tenant credential read.
   */
  $txpcfg['db'] = $_SERVER['db_name'];
  $txpcfg['user'] = $_SERVER['db_user'];
  $txpcfg['pass'] = $_SERVER['db_passwd'];
  $txpcfg['host'] = $_SERVER['db_host'] . (!empty($_SERVER['db_port']) && $_SERVER['db_port'] != '3306' ? ':' . $_SERVER['db_port'] : '');
}
/**
 * Consumed; clear so a credential never surfaces in phpinfo() or a stray
 * var_dump(), and so a later subprocess in the same run cannot inherit a
 * stale value.
 */
unset($_SERVER['db_type']);
unset($_SERVER['db_user']);
unset($_SERVER['db_passwd']);
unset($_SERVER['db_host']);
unset($_SERVER['db_port']);
unset($_SERVER['db_name']);
unset($_SERVER['db_creds_urlencoded']);
<?php else: ?>
$txpcfg['db'] = '<?php print addcslashes($this->creds['db_name'], "'\\"); ?>';
$txpcfg['user'] = '<?php print addcslashes($this->creds['db_user'], "'\\"); ?>';
$txpcfg['pass'] = '<?php print addcslashes($this->creds['db_passwd'], "'\\"); ?>';
$txpcfg['host'] = '<?php print addcslashes($this->creds['db_host'] . (!empty($this->creds['db_port']) && $this->creds['db_port'] != '3306' ? ':' . $this->creds['db_port'] : ''), "'\\"); ?>';
<?php endif; ?>
$txpcfg['table_prefix'] = '';
$txpcfg['txpath'] = '<?php print addcslashes($txp_txpath, "'\\"); ?>';
$txpcfg['dbcharset'] = 'utf8mb4';
$txpcfg['table_collation'] = 'utf8mb4_unicode_ci';
$txpcfg['dbengine'] = 'InnoDB';
$txpcfg['multisite_root_path'] = '<?php print addcslashes($txp_multisite_root, "'\\"); ?>';
$txpcfg['admin_url'] = '<?php print addcslashes($txp_admin_url, "'\\"); ?>';
$txpcfg['cookie_domain'] = '';
if (!defined('txpath')) { define('txpath', $txpcfg['txpath']); }

/**
 * If the external request was HTTPS but the internal request is HTTP -- the
 * box-level SSL catch-all serves cert-less vhosts by proxying to the plain
 * vhost with X-Forwarded-Proto as the signal -- set $_SERVER['HTTPS'] so
 * Textpattern derives the right PROTOCOL (publish.php reads only that var):
 * https asset/link URLs and the secure cookie flag. The same contract as the
 * Drupal and Backdrop settings templates; sites with their own SSL vhost get
 * fastcgi_param HTTPS on directly and never enter this branch.
 */
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && isset($_SERVER['REQUEST_SCHEME'])) {
  if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' && $_SERVER['REQUEST_SCHEME'] == 'http') {
    $_SERVER['HTTPS'] = 'on';
  }
}
