<?php
/**
 * @file
 * Template for a Textpattern multisite private/config.php.
 *
 * Shape mirrors TXP's own setup_makeConfig() output plus the keys it never
 * emits but Percona 8.4 + the fleet require: dbengine (the TXP default is
 * MyISAM), table_collation (utf8mb4_unicode_ci exists on both Percona 5.7 and
 * 8.4; the 8.4 server default utf8mb4_0900_ai_ci does not exist on 5.7 --
 * mydumper moves between fleet halves), and NO client_flags key at all (TXP's
 * isset() test would discard its own FOUND_ROWS default).
 */
print '<?php' ?>

/**
 * @file Textpattern config.php (Aegir-managed; re-rendered on every verify.
 * Manual edits will be lost.)
 *
 * Generated by Aegir <?php print $this->version; ?> on <?php print date('r'); ?>.
 */
$txpcfg['db'] = '<?php print addcslashes($this->creds['db_name'], "'\\"); ?>';
$txpcfg['user'] = '<?php print addcslashes($this->creds['db_user'], "'\\"); ?>';
$txpcfg['pass'] = '<?php print addcslashes($this->creds['db_passwd'], "'\\"); ?>';
$txpcfg['host'] = '<?php print addcslashes($this->creds['db_host'] . (!empty($this->creds['db_port']) && $this->creds['db_port'] != '3306' ? ':' . $this->creds['db_port'] : ''), "'\\"); ?>';
$txpcfg['table_prefix'] = '';
$txpcfg['txpath'] = '<?php print addcslashes($txp_txpath, "'\\"); ?>';
$txpcfg['dbcharset'] = 'utf8mb4';
$txpcfg['table_collation'] = 'utf8mb4_unicode_ci';
$txpcfg['dbengine'] = 'InnoDB';
$txpcfg['multisite_root_path'] = '<?php print addcslashes($txp_multisite_root, "'\\"); ?>';
$txpcfg['admin_url'] = '<?php print addcslashes($txp_admin_url, "'\\"); ?>';
$txpcfg['cookie_domain'] = '';
if (!defined('txpath')) { define('txpath', $txpcfg['txpath']); }

/**
 * If the external request was HTTPS but the internal request is HTTP -- the
 * box-level SSL catch-all serves cert-less vhosts by proxying to the plain
 * vhost with X-Forwarded-Proto as the signal -- set $_SERVER['HTTPS'] so
 * Textpattern derives the right PROTOCOL (publish.php reads only that var):
 * https asset/link URLs and the secure cookie flag. The same contract as the
 * Drupal and Backdrop settings templates; sites with their own SSL vhost get
 * fastcgi_param HTTPS on directly and never enter this branch.
 */
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && isset($_SERVER['REQUEST_SCHEME'])) {
  if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' && $_SERVER['REQUEST_SCHEME'] == 'http') {
    $_SERVER['HTTPS'] = 'on';
  }
}
